dist: xenial  # required for Python 3.7
language: python
env:
  global:
    - PIP_DEPS="flake8 pytest coveralls pytest-cov"
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install --upgrade pip
  - pip --version
  - travis_retry pip install -e .[dev]
  - pip install codacy-coverage
  - pip install 'pytest-cov>=2.4.0,<2.6'
script:
  - flake8 `find . -name \*.py | grep -v setup.py | grep -v
    version.py | grep -v __init__.py | grep -v /doc/`
  - travis_wait 30 py.test --pyargs afqinsight --cov-report term-missing --cov-config .coveragerc --cov=afqinsight
  - coverage xml
after_success:
  - python-codacy-coverage -r coverage.xml
